# version: "3.8"

# services:
#   app:
#     container_name: frontend
#     image: frontend
#     ports:
#       - 80:80
#     build:
#       context: .
#       target: production

version: '3.8'

services:
  app:
    container_name: frontend
    image: frontend
    ports:
      - 80:80
    build:
      context: .
      target: production
    networks:
      - forum_network
networks:
  forum_network:
