version: '3.9'

services:
  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - forum_network
networks:
  forum_network:

volumes:
  redis_data:
    external: false