version: '3.9'

services:
  nginx:
    build: ./configs/nginx
    container_name: nginx
    ports:
      - 80:80
    networks:
      - forum_network
    volumes:
      - media:/home/forum/app/public/media

networks:
  forum_network:

volumes:
  media:
    external:
      name: forum_media    
