version: '3.9'

services:
  web-dev:
    build: .
    container_name: web-dev
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/Forum
    ports:
      - 8000:8000
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ENGINE=${ENGINE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - EMAIL_BACKEND=${EMAIL_BACKEND}"
      - EMAIL_HOST=${EMAIL_HOST}"
      - EMAIL_PORT=${EMAIL_PORT}"
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}"
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}"
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}"
    networks:
      - forum_network
  frontend:
    container_name: frontend
    image: frontend
    ports:
      - 3000:3000
    build:
      context: ./FrontEnd
      target: production
    networks:
      - forum_network

networks:
  forum_network:
