name: Django CD DEV
on: workflow_dispatch

env:
    DEBUG: ${{ vars.DEV_DEBUG }}
    SECRET_KEY: ${{ secrets.DEV_SECRET_KEY }}
    ENGINE: ${{ vars.ENGINE }}
    DB_HOST: ${{ vars.POSTGRES_HOST }}
    DB_PORT: ${{ vars.POSTGRES_PORT }}
    PG_DB: ${{ vars.DEV_DB }}
    PG_USER: ${{ vars.POSTGRES_USER }}
    PG_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    POSTGRES_DB: ${{ vars.POSTGRES_DB }}
    EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST: ""
    EMAIL_PORT: ""
    EMAIL_USE_TLS: ""
    EMAIL_HOST_USER: ""
    EMAIL_HOST_PASSWORD: ""

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker compouse DOWN old Django container
        run:  docker compose -f docker-compose.dev.yml down -v
      - name: Docker compouse UP Django container
        run: docker compose -f docker-compose.dev.yml up -d --build
      - name: Docker compouse MIGRATE models
        run: docker compose -f docker-compose.dev.yml exec web-dev python manage.py migrate --noinput
      
      - name: Clean up old docker resources 
        run: |
          docker container prune -f
          docker image prune -f
