name: Testing FE

on: pull_request

jobs:
  build_and_test:
    name: Testing # job name (unique id)
    runs-on: ubuntu-latest # on which machine to run
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          cd FrontEnd
          npm install

      - name: Code Testing
        run: |
          cd FrontEnd
          npm test